# Generated by Django 3.0.2 on 2021-10-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211025_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.TextField(default=12345),
            preserve_default=False,
        ),
    ]
